# -*- coding: utf-8 -*-
"""ChatBotDemo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mY4_YzDxfxamCtU77oEdGIsKDzD1XxAL
"""

import re
import random

class MyDemoBot:
  ### User Disapproval Response

  negative_responses = ("no","not a chance ","sorry","bye")

  ### terminate conversation

  exit_command = ("stop","pause","quit","later","goodbye","later")

  ### Start Interactin with ValeedChatBotDemo

  random_question = (
    "Hello Welcome to Demo ChatBot App ",
    "We are ready to serve you 24/7"
    "How can I help you",
    "Lets start with quick conversation",
    "Valeed Demo Chatbot is here to solve your query"
  )

  def __init__(self):
    self.ValeedQues = { 'describe_valeed_intent': r'.*\s*your Machine.*',
                        'answer_Why_intent': r'why\sare.*',
                         'about_valeedbot': r'.*\s*valeedbot'
                         }

  def greet(self):
    self.name = input("What is your name?\n")
    will_help = input(
        f"Hi {self.name}, I am Rule-Bot . Will you help me learn about your Machine Learning?\n")
    if will_help in self.negative_responses:
      print("Ok, ValeedChatBot End of the  day!")
      return
    self.chat()

  def make_exit(self, reply):
    for command in self.exit_command:
      if reply == command:
        print("Okay,see you soon, have a nice  Day ValeedChatBot day!")
        return True

  def chat(self):
   reply = input(random.choice(self.random_question)).lower()
   while not self.make_exit(reply):
      reply = input(self.match_reply(reply))

  def match_reply(self, reply):
    for key, value in self.ValeedQues.items():
      intent = key
      regex_pattern = value
      found_match = re.match(regex_pattern, reply)
      if found_match and intent == 'describe_valeed_intent':
        return self.describe_valeed_intent()
      elif found_match and intent == 'answer_why_intent':
          return self.answer_why_intent()
      elif found_match and intent == 'about_valeedbot':
          return self.about_valeedbot()
    if not found_match:
      return self.no_match_intent()

  def describe_valeed_intent(self):
     responses = ("My ValeedChatBot is excellent way for python Machinelearning .\n",
                 "I hope you enjoy ValeedChatBot.\n")
     return random.choice(responses)

  def answer_why_intent(self):
      responses = ("ValeedChatBot provide every solution to question needed.\n",
                 "And helping to predict the big ValeedData.\n")
      return random.choice(responses)

  def about_valeedbot(self):
      responses = ("ValeedChat Bot is effective .\n",
                 "It helps to predict the outcomes of values through valeedchatbot.\n")
      return random.choice(responses)

  def no_match_intent(self):
      responses = ("Please enter some Faq  question .\n",
                 "Ohk ValeedChatBot.\n")
      return random.choice(responses)



RuleBot = MyDemoBot()
RuleBot.greet()